export * from './cabezote/Cabezote'
export * from './services-Slider/ServicesSlider'
export * from './project-Form/ProjectForm'
export * from './modal-Project/ModalProject'
export * from './cards-Services/card1/Card1'
export * from './cards-Services/card2/Card2'
export * from './cards-Services/card3/Card3'
export * from './button-first/ButtonFirst'
export * from './button-second/ButtonSecond'
export * from './ContactSection/ContactSection'
export * from './footer/Footer'
export * from './header/Header'
export * from './team-card/TeamCard'
export * from './team-interaction/TeamInteraction'
export * from './team-modal/ModalTeam'

